### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by dungpham98** [DevPranjal/mico-first-principles#2]
Hi,

I really like your work in Membership Inference Attack and am also trying to recreate the result of your approach. However, I could not find the CIFAR10 dataset which is the same as in the competition. If possible, can you provide it? Thank you.

**Comment by DevPranjal** [comment]
Hello! Thank you for going through our submission. The challenge problem and data can be accessed here: https://github.com/microsoft/MICO.
